GET http://localhost:8000?status=202

HTTP/1.1 202 Accepted

###

GET http://localhost:8000?body=hello

HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain;charset=UTF-8

hello

###
GET http://localhost:8000?delay=200&body=hello

HTTP/1.1 200 OK

###


GET http://0.0.0.0:8000/?status=200&body=%3Ch1%3Ehola%3C%2Fh1%3E&headers=%7B%0A++%22Content-Type%22%3A+%22text%2Fhtml%22%0A%7D

HTTP/1.1 200 OK

###

--
id: adjective
---
GET http://localhost:8000/word/adjective
Accepted-Language: es

HTTP/1.1 200 OK

###

POST http://localhost:8000/pong
data-test: pong
content-type: text/plain; charset=UTF-8

body

HTTP/1.1 200 OK
data-test: pong
content-type: text/plain; charset=UTF-8

body

###

GET http://localhost:8000/string/hexadecimal/%7B%22length%22:1000%7D