@host=http://localhost:8000
# @host=https://faker.deno.dev
###
POST {{host}}/pong
          ?status=201
          &delay=100
          &body=willBeIgnored
          &headers={"x-hola":"mundo"}
X-hello: world
content-type: text/plain

{"a":1}

###

GET {{host}}/name/firstName
###
GET {{host}}/name/firstName
accept-language: en

###
GET {{host}}/phone/phoneNumber/###-###-####
###
GET {{host}}/?status=204&body=ping&delay=1000
###
GET {{host}}/helpers/createTransaction

###
GET {{host}}/helpers/fake/Good Morning "{{name.firstName}}"!

###
GET {{host}}/finance/account/4
###
{{host}}/helpers/unique/datatype/number/{"max":4,"min":1}

###
{{host}}/git/commitEntry?status=569
