@host=http://localhost:8000
###
GET {{host}}/pong
Accept-Language: es
x-hello: hola

body


###
GET {{host}}/?status=204&body=ping&delay=1000

###
GET {{host}}/random/image

###
GET {{host}}/finance/account/4

###
/lorem/sentences/2

###
/helpers/userCard

###
/ups/hola

###
/datatype/number/{"max":2,"min":1}

###
/git/commitEntry?status=569
